// Add empty declarations for modules that TypeScript can't find
declare module 'accepts' {}
declare module 'bcrypt' {}
declare module 'body-parser' {}
declare module 'connect' {}
declare module 'cors' {}
declare module 'express-serve-static-core' {}
declare module 'http-errors' {}
declare module 'jsonwebtoken' {}
declare module 'long' {}
declare module 'mime' {}
declare module 'ms' {}
declare module 'node-fetch' {}
declare module 'qs' {}
declare module 'range-parser' {}
declare module 'send' {}
declare module 'serve-static' {}
declare module 'long' {}
declare module 'mime' {}